config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Dir.glob('config/routes/v*').each do |version_routes|
  require Rails.root.join(version_routes)
end

require Rails.root.join('config/routes/admin')

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /en|pl/ do
    root 'static_pages#home'

    namespace :api do
      scope ':version', version: /v1/ do
        extend Routes::V1
      end
    end

    devise_for :users,
               class_name: '::User',
               path: 'admin',
               skip: %i[confirmations unlocks],
               controllers: {
                 sessions: 'admin/authentication/sessions',
                 registrations: 'admin/authentication/registrations'
               }

    namespace :admin do
      extend Routes::Admin
    end

    resources :restaurants, module: :restaurants do
      resources :menus, only: :show
    end

    resources :aggregated_menus, only: :index 
    resources :orders

    namespace :third_party do
      namespace :payments do
        resources :stripe_payments, only: [] do
          collection do
            get 'stripe_refresh'
            get 'stripe_return'
            post 'create_connected_account'
          end
        end
      end
    end

    resources :webhooks, only: [:create]
  end

  get 'redirect/:id', to: 'qr_redirects#show'
  post 'new-restaurants-registeration', to: 'new_registrations#create', as: :new_restaurant_registration
end

app/controllers/admin/aggregated_menus_controller.rb
# frozen_string_literal: true

class Admin::AggregatedMenusController < ::Admin::ApplicationController
  before_action :set_restaurant

  def index; end

  def update
    restaurant = Restaurants::Update.new(
      params: aggregated_menu_params, 
      restaurant: @restaurant
    ).call

    error_or_redirect(
      object: restaurant,
      success_path: admin_aggregated_menus_path(q: params[:q]),
      failure_path: admin_aggregated_menus_path,
      i18n_scope: 'controllers/admin/admin_aggregated_menus_controller'
    )
  end

  private

  def set_restaurant
    @restaurant ||= current_restaurant
  end

  def aggregated_menu_params
    params
      .require(:restaurant)
      .permit(
        :restaurant_id,
        :aggregated_menu_title,
        :aggregated_menu_background,
        :aggregated_menu_font,
        :aggregated_menu_footer,
        :aggregated_menu_animation,
        :aggregated_menu_text_color,
        :aggregated_menu_card_color
      )
  end
end

app/controllers/aggregated_menus_controller.rb
# frozen_string_literal: true

class AggregatedMenusController < ApplicationController
  layout 'menu_application'
  before_action :set_restaurant, only: :index

  def index
    redirect_to root_path unless @restaurant
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find_by(slug: params[:id])
  end
end

app/views/admin/aggregated_menus/index.slim
- i18n_scope = "views.admin.aggregated_menus.index"
- content_for :title, "Aggregated Menu"

scss:

section.section.is-title-bar
  .level
    .level-left
      .level-item
        ul
          li = t 'admin', scope: i18n_scope
          li Aggregated Menu
section.hero.is-hero-bar
  .hero-body
    .level
      .level-left
        .level-item
          h1.title = t 'aggregated_menu', scope: i18n_scope
      .level-right
        .level-item
          = link_to "Preview", "#{aggregated_menus_url}?id=#{@restaurant.slug}"

section.section.is-main-section
  .columns
    .column.is-5
      .card
        header.card-header
          p.card-header-title Properties
        .card-content
          = form_with(model: @restaurant, url: admin_aggregated_menu_path(@restaurant)) do |form|
            = render 'common/devise_notifications', locals: { resource: @restaurant }

            .field
              .field-label.is-normal
                label.label Title
              .field-body
                .field
                  .control
                    = form.text_field :aggregated_menu_title, value: "#{@restaurant.aggregated_menu_title || @restaurant.name}", class: "input"
                  p.help Required. Main title
            .columns.is-multiline
              .column
                .field
                  .field-label.is-normal
                    label.label Background color
                  .field-body
                    .field
                      .control
                        = form.color_field :aggregated_menu_background, value: "#{@restaurant.aggregated_menu_background}", class: "input"
              .column
                .field
                  .field-label.is-normal
                    label.label Font color
                  .field-body
                    .field
                      .control
                        = form.color_field :aggregated_menu_text_color, value: "#{@restaurant.aggregated_menu_text_color}", class: "input"

              .column
                .field
                  .field-label.is-normal
                    label.label Card color
                  .field-body
                    .field
                      .control
                        = form.color_field :aggregated_menu_card_color, value: "#{@restaurant.aggregated_menu_card_color}", class: "input"
            .field
              .field-label.is-normal
                label.label Footer text
              .field-body
                .field
                  .control
                    = form.text_field :aggregated_menu_footer, value: "#{@restaurant.aggregated_menu_footer}", class: "input"

            .field
              .field-label.is-normal
                label.label Animation
              .field-body
                .field
                  .control.select.is-multiple.is-fullwidth
                    = form.select :aggregated_menu_animation, %w[zoom-in zoom-out spin left-to-right flip], { include_blank: false }, { :class => "select is-fullwidth" }
            
            = form.submit "Save", class: 'button is-primary'

    .column.is-7
      .card
        header.card-header
          p.card-header-title Preview
        .card-image
          iframe style="height: 50vh; width: 100%" src="#{aggregated_menus_url}?id=#{@restaurant.slug}" 
 