config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Dir.glob('config/routes/v*').each do |version_routes|
  require Rails.root.join(version_routes)
end

require Rails.root.join('config/routes/admin')

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /en|pl/ do
    root 'static_pages#home'

    namespace :api do
      scope ':version', version: /v1/ do
        extend Routes::V1
      end
    end

    devise_for :users,
               class_name: '::User',
               path: 'admin',
               skip: %i[confirmations unlocks],
               controllers: {
                 sessions: 'admin/authentication/sessions',
                 registrations: 'admin/authentication/registrations'
               }

    namespace :admin do
      extend Routes::Admin
    end

    resources :restaurants, module: :restaurants do
      resources :menus, only: :show
    end

    resources :aggregated_menus, only: :index 
    resources :orders

    namespace :third_party do
      namespace :payments do
        resources :stripe_payments, only: [] do
          collection do
            get 'stripe_refresh'
            get 'stripe_return'
            post 'create_connected_account'
          end
        end
      end
    end

    resources :webhooks, only: [:create]
  end

  get 'redirect/:id', to: 'qr_redirects#show'
  post 'new-restaurants-registeration', to: 'new_registrations#create', as: :new_restaurant_registration
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to  :restaurant,    class_name: '::Restaurant'
  belongs_to  :table,         class_name: '::Table'

  belongs_to  :employee,      class_name: '::Employee',
                              foreign_key: :user_id,
                              optional: true,
                              inverse_of: :user_id

  has_many    :line_items,    class_name: '::LineItem',
                              dependent: :destroy

  has_many    :payments,      class_name: '::Payment',
                              dependent: :destroy

  enum status: { pending: 0, completed: 1, cancelled: 2, refunded: 3 }

  monetize :tips_total,       as: :tips_total_cents
  monetize :order_total,      as: :order_total_cents
  monetize :discount_amount,  as: :discount_amount_cents

  validates :tips_total,      numericality: true
  validates :order_total,     numericality: true
  validates :discount_amount, numericality: true
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

class Admin::OrdersController < ::Admin::ApplicationController
  POLICY_CLASS = OrderPolicy
  before_action :set_order, only: %i[update destroy show]

  def index
    authorize((params[:restaurant_id] || current_restaurant.id), :index?)

    @q = current_restaurant.orders.ransack params[:q]
    @orders = @q.result.page(params[:page]).per(params[:per] || 5)
  end

  def update; end

  def show; end

  def destroy; end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index; end
  def create; end
  def show; end
end

app/views/admin/orders/_order_row.slim
- order = locals[:order]

tr
  td
  td = order.id
  td = order.order_uuid.split("-")[0]
  td = order.table
  td.has-text-grey.is-abbr-like = I18n.l(order.created_at, format: "%b %d, %Y", locale: I18n.locale)
  td = order.status


  / td = restaurant.managers.map(&:to_s)
  / td = restaurant.city
  / td.is-actions-cell
  /   .buttons.is-right
  /     = button_to admin_restaurant_path(restaurant.id), method: :get, class: "button is-small is-primary" do 
  /       span.icon
  /         i.mdi.mdi-eye
  /     button.jb-modal.button.is-warning.is-small data-target="edit_restaurant_modal_#{restaurant.id}"
  /       span.icon
  /         i.mdi.mdi-pencil
  /     = button_to admin_restaurant_path(restaurant.id), method: :delete, class: "button is-small is-danger" do 
  /       span.icon
  /         i.mdi.mdi-trash-can

  /   = render "common/edit_resource_modal", locals: { \
  /     resource: restaurant, \
  /     resource_path: admin_restaurant_path(restaurant), \
  /     resource_form_path: "admin/restaurants/form", \
  /     i18n_scope: locals[:i18n_scope], \
  /     method: :put \
  /   }

app/views/admin/orders/index.slim
- i18n_scope = "views.admin.restaurants.index"
- content_for(:title, "Orders")

section.section.is-title-bar
  .level
    .level-left
      .level-item
        ul
          li = t 'admin', scope: i18n_scope
          li = t 'restaurants', scope: i18n_scope
section.hero.is-hero-bar
  .hero-body
    .level
      .level-left
        .level-item
          h1.title = t('orders', scope: i18n_scope)
      .level-right
        .level-item
          button.jb-modal.button.is-primary.is-small data-target="new_order_modal"
            b New Order

section.section.is-main-section
  .card.has-table.has-mobile-sort-spaced
    header.card-header
      p.card-header-title
        span.icon
          i.mdi.mdi-account-multiple
        = t 'all_orders', scope: i18n_scope
      a.card-header-icon href="#" 
        span.icon
          i.mdi.mdi-reload
    .card-content
      .b-table.has-pagination
        .table-wrapper.has-mobile-cards
          .table-container style="overflow-x: auto; position:  relative"
            table.table.is-fullwidth.is-striped.is-hoverable.is-sortable.is-fullwidth
              thead
                tr
                  th
                  th = sort_link @q, :id, Order.human_attribute_name(:id)
                  th = sort_link @q, :order_uuid, Order.human_attribute_name(:order_uuid)
                  th = sort_link @q, :table, Order.human_attribute_name(:table)
                  th = sort_link @q, :created_at, Order.human_attribute_name(:created_at)
                  th = sort_link @q, :status, Order.human_attribute_name(:status)
                  th
              tbody
                - @orders.each do |order|
                  = render 'order_row', locals: { order: order, i18n_scope: i18n_scope }
  = paginate @orders

  / = render 'common/new_resource_modal', locals: { \
  /   resource: Restaurant.new(managers: [current_user]), \
  /   resource_path: admin_restaurants_path, \
  /   resource_form_path: "admin/restaurants/form",\
  /   i18n_scope: i18n_scope \
  / }