config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Dir.glob('config/routes/v*').each do |version_routes|
  require Rails.root.join(version_routes)
end

require Rails.root.join('config/routes/admin')

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /en|pl/ do
    root 'static_pages#home'

    namespace :api do
      scope ':version', version: /v1/ do
        extend Routes::V1
      end
    end

    devise_for :users,
               class_name: '::User',
               path: 'admin',
               skip: %i[confirmations unlocks],
               controllers: {
                 sessions: 'admin/authentication/sessions',
                 registrations: 'admin/authentication/registrations'
               }

    namespace :admin do
      extend Routes::Admin
    end

    resources :restaurants, module: :restaurants do
      resources :menus, only: :show
    end

    resources :aggregated_menus, only: :index 
    resources :orders

    namespace :third_party do
      namespace :payments do
        resources :stripe_payments, only: [] do
          collection do
            get 'stripe_refresh'
            get 'stripe_return'
            post 'create_connected_account'
          end
        end
      end
    end

    resources :webhooks, only: [:create]
  end

  get 'redirect/:id', to: 'qr_redirects#show'
  post 'new-restaurants-registeration', to: 'new_registrations#create', as: :new_restaurant_registration
end

app/controllers/admin/settings_controller.rb
# frozen_string_literal: true

class Admin::SettingsController < ::Admin::ApplicationController
  def index; end

  def link_stripe_account; end
end

app/controllers/api/v1/settings_controller.rb
# frozen_string_literal: true

class Api::V1::SettingsController < ApplicationController
  def show; end
  def update; end
end

app/views/admin/settings/_manager_settings.slim
- stripe_client_id = locals[:stripe_client_id]

section.section.is-main-section
  .tabs
    ul
      li.is-active#account_settings
        a Account Settings
      li
        a Personal Settings
      li 
        a Global Settings

  .tab-sections
    .section.p-0#account_settings
      - if stripe_client_id
        p You're connected with a stripe account successfully!
        = stripe_client_id&.safe_value
      - else
        = form_with url: create_connected_account_third_party_payments_stripe_payments_path + ".js", remote: true, local: false, id: 'stripe_connected_account' do |f|
          = button_tag type: :submit, class: 'button is-primary' do
            span.icon
              i.mdi.mdi-cash-plus
            span Connect stripe

      /= form_with url: create_connected_account_third_party_payments_stripe_payments_path + ".js", remote: true, local: false, id: 'stripe_connected_account' do |f|
          = button_tag type: :submit, class: 'button is-primary' do
            span.icon
              i.mdi.mdi-cash-plus
            span Connect stripe

app/views/admin/settings/index.slim
- i18n_scope = "views.admin.settings.index"
- content_for :title, "Settings"
= javascript_include_tag "stripe_connected_account", "data-turbo-track": "reload", defer: true, type: "module"

section.section.is-title-bar
  .level
    .level-left
      .level-item
        ul
          li = t 'admin', scope: i18n_scope
          li = t 'settings', scope: i18n_scope
section.hero.is-hero-bar
  .hero-body
    .level
      .level-left
        .level-item
          h1.title = t('settings', scope: i18n_scope)
      .level-right style=("display: none;") 
        .level-item

= render 'manager_settings', locals: { \
  stripe_client_id: ::Config.find_by( \
    key: 'third_party.stripe.connect_client_id', \
    restaurant_id: current_restaurant \
  )} if current_user.manager?
= render 'employee_settings' if current_user.employee?