config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Dir.glob('config/routes/v*').each do |version_routes|
  require Rails.root.join(version_routes)
end

require Rails.root.join('config/routes/admin')

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /en|pl/ do
    root 'static_pages#home'

    namespace :api do
      scope ':version', version: /v1/ do
        extend Routes::V1
      end
    end

    devise_for :users,
               class_name: '::User',
               path: 'admin',
               skip: %i[confirmations unlocks],
               controllers: {
                 sessions: 'admin/authentication/sessions',
                 registrations: 'admin/authentication/registrations'
               }

    namespace :admin do
      extend Routes::Admin
    end

    resources :restaurants, module: :restaurants do
      resources :menus, only: :show
    end

    resources :aggregated_menus, only: :index 
    resources :orders

    namespace :third_party do
      namespace :payments do
        resources :stripe_payments, only: [] do
          collection do
            get 'stripe_refresh'
            get 'stripe_return'
            post 'create_connected_account'
          end
        end
      end
    end

    resources :webhooks, only: [:create]
  end

  get 'redirect/:id', to: 'qr_redirects#show'
  post 'new-restaurants-registeration', to: 'new_registrations#create', as: :new_restaurant_registration
end

app/views/common/_devise_notifications.html.erb
<% resource ||= locals[:resource] %>

<% if resource.errors.any? %>
  <div class="notification is-danger">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <div>
            <span class="icon"><i class="mdi mdi-buffer default"></i></span>
            <b>
              <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
              %>
            </b>
            <div class="content">
              <ul>
                <% resource.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="level-right">
        <button type="button" class="button is-small is-white">
          <span> Dismiss </span>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/common/_devise_shared_links.slim
- i18n_scope = "views.common.devise_shared_links"

- if controller_name != 'sessions'
  = link_to t('log_in', scope: i18n_scope), new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t('sign_up', scope: i18n_scope), new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t('forgot_password', scope: i18n_scope), new_password_path(resource_name)

app/views/common/_edit_resource_modal.slim
- resource = locals[:resource]
- resource_path = locals[:resource_path]
- resource_form_path = locals[:resource_form_path]

- i18n_scope = locals[:i18n_scope]

.modal id="edit_#{resource.class.to_s.downcase}_modal_#{resource.id}"
  .modal-background.jb-modal-close
  .modal-card
    header.modal-card-head
      p.modal-card-title = resource.to_s
      button.delete.jb-modal-close aria-label="close"
    section.modal-card-body
      = render resource_form_path, locals: { \
        resource: resource, \
        url: resource_path, \
        method: :put \
      }

    footer.modal-card-foot
      button.button.jb-modal-close Cancel
      = link_to t("update_#{resource.class.to_s.downcase}", scope: i18n_scope), {}, class: "modal-form-submit button is-primary"
  button.modal-close.is-large.jb-modal-close aria-label="close"

app/views/common/_invite_referral_modal.slim
- resource = locals[:resource]
- resource_path = locals[:resource_path]
- resource_form_path = locals[:resource_form_path]

- i18n_scope = locals[:i18n_scope]

.modal id="new_#{resource.class.to_s.downcase}_modal"
  .modal-background.jb-modal-close
  .modal-card
    header.modal-card-head
      p.modal-card-title = t "new_#{resource.class.to_s.downcase}", scope: i18n_scope
      button.delete.jb-modal-close aria-label="close"
    section.modal-card-body
      = render resource_form_path, locals: { \
        resource: resource, \
        url: resource_path, \
        method: :post \
      }

    foote.modal-card-foot
      button.button.jb-modal-close = t 'cancel', scope: i18n_scope
      = link_to t("create_#{resource.class.name}", scope: i18n_scope), {}, class: "modal-form-submit button is-primary"
  button.modal-close.is-large.jb-modal-close aria-label="close"

app/views/common/_new_resource_modal.slim
- resource = locals[:resource]
- resource_path = locals[:resource_path]
- resource_form_path = locals[:resource_form_path]

- i18n_scope = locals[:i18n_scope]

.modal id="new_#{resource.class.to_s.downcase}_modal"
  .modal-background.jb-modal-close
  .modal-card
    header.modal-card-head
      p.modal-card-title = t "new_#{resource.class.to_s.downcase}", scope: i18n_scope
      button.delete.jb-modal-close aria-label="close"
    section.modal-card-body
      = render resource_form_path, locals: { \
        resource: resource, \
        url: resource_path, \
        method: :post \
      }

    foote.modal-card-foot
      button.button.jb-modal-close = t 'cancel', scope: i18n_scope
      = link_to t("create_#{resource.class.name}", scope: i18n_scope), {}, class: "modal-form-submit button is-primary"
  button.modal-close.is-large.jb-modal-close aria-label="close"